local prefix = "packages.mobile.pkg.mobile_rare.skills."

return {
  require(prefix .. "yingjian"),
  require(prefix .. "shixin"),
  require(prefix .. "dujin"),
  require(prefix .. "fenyin"),
  require(prefix .. "kuangcai"),
  require(prefix .. "shejian"),
  require(prefix .. "shanjia"),
  require(prefix .. "pingcai"),
  require(prefix .. "yinshi"),
  require(prefix .. "jingxie"),
  require(prefix .. "qiaosi"),
  require(prefix .. "zhengjing"),
  require(prefix .. "yufeng"),
  require(prefix .. "tianshu"),
  require(prefix .. "danggu"),
  require(prefix .. "mowang"),

  require(prefix .. "taoluan"),
  require(prefix .. "chiyan"),
  require(prefix .. "zimou"),
  require(prefix .. "picai"),
  require(prefix .. "yaozhuo"),
  require(prefix .. "xiaolu"),
  require(prefix .. "kuiji"),
  require(prefix .. "chihe"),
  require(prefix .. "niqu"),
  require(prefix .. "miaoyu"),

  require(prefix .. "quchong"),
  require(prefix .. "quchong_active"),
  require(prefix .. "xunjie"),
  require(prefix .. "renjie"),
  require(prefix .. "baiyin"),
  require(prefix .. "lianpo"),
  require(prefix .. "jilue"),

  require(prefix .. "weifeng"),
  require(prefix .. "zhilve"),
  require(prefix .. "zhiyan"),
  require(prefix .. "jinfan"),
  require(prefix .. "jinfan_active"),
  require(prefix .. "sheque"),
  require(prefix .. "shidi"),
  require(prefix .. "yishi"),
  require(prefix .. "qishe"),
  require(prefix .. "guli"),
  require(prefix .. "aosi"),
  require(prefix .. "huiyao"),
  require(prefix .. "quesong"),
  require(prefix .. "xiongjin"),
  require(prefix .. "zhenbian"),
  require(prefix .. "baoxi"),
  require(prefix .. "baoxi_viewas"),
}
