local prefix = "packages.mobile.pkg.mobile_lxxh.skills."

return {
  require(prefix .. "qianlong"),
  require(prefix .. "weitong"),
  require(prefix .. "qingzheng"),
  require(prefix .. "jiushi"),
  require(prefix .. "fangzhu"),
  require(prefix .. "juejin"),
  require(prefix .. "cuizhen"),
  require(prefix .. "kuili"),
  require(prefix .. "zuoyou"),
  require(prefix .. "shishou"),
  require(prefix .. "kuangli"),
  require(prefix .. "xiongsi"),
  require(prefix .. "panxiang"),
  require(prefix .. "chenjie"),
  require(prefix .. "beiming"),
  require(prefix .. "choumang"),
  require(prefix .. "bifeng"),
  require(prefix .. "suwang"),
  require(prefix .. "beini"),
  require(prefix .. "dingfa"),
  require(prefix .. "xiezheng"),
  require(prefix .. "qiantun"),
  require(prefix .. "zhaoxiong"),
  require(prefix .. "weisi"),
  require(prefix .. "dangyi"),
}
