local prefix = "packages.mobile.pkg.mobile_shiji.skills."

return {
  require(prefix .. "qiai"),
  require(prefix .. "shanxi"),
  require(prefix .. "shameng"),
  require(prefix .. "jianzhan"),
  require(prefix .. "duoji"),
  require(prefix .. "jianyu"),
  require(prefix .. "qinzheng"),
  require(prefix .. "wuku"),
  require(prefix .. "sanchen"),
  require(prefix .. "miewu"),
  require(prefix .. "dingyi"),
  require(prefix .. "zuici"),
  require(prefix .. "fubi"),
  require(prefix .. "wanwei"),
  require(prefix .. "yuejian"),
  require(prefix .. "huishi"),
  require(prefix .. "tianyi"),
  require(prefix .. "huishig"),
  require(prefix .. "zuoxing"),
  require(prefix .. "tianzuo"),
  require(prefix .. "lingce"),
  require(prefix .. "dinghan"),

  require(prefix .. "yingba"),
  require(prefix .. "fuhai"),
  require(prefix .. "pinghe"),
  require(prefix .. "dulie"),
  require(prefix .. "powei"),
  require(prefix .. "powei_active"),
  require(prefix .. "shenzhuo"),
}
